export function extractGoogleSheetId(input: string): string | null {
  const trimmed = input.trim();
  if (!trimmed) return null;
  const urlMatch = trimmed.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);
  if (urlMatch?.[1]) return urlMatch[1];
  if (/^[a-zA-Z0-9-_]{20,}$/.test(trimmed)) return trimmed;
  return null;
}

export function sanitizeInternalPath(value: string | null | undefined, fallback: string): string {
  if (!value || !value.startsWith('/')) return fallback;
  return value;
}

export interface OniTemplateSheet {
  title: string;
  headers: string[];
}

/**
 * Canonical schema v1 for ONI Google Sheet DB.
 *
 * Rules:
 * - Oni reads/writes by header NAME, never by column index.
 * - New columns are always appended to the END of a tab — safe to add without migration.
 * - IDs use human-readable prefixes (P-001, C-001, ORD-2025-0001) generated by Oni.
 * - The Settings tab carries `schema_version` so Oni can detect and auto-migrate old sheets.
 * - Computed/derived values (e.g. customer total_spent) are NOT stored; calculated on demand.
 */
export function buildOniTemplateSheets(): OniTemplateSheet[] {
  return [
    {
      // Danh mục hàng hóa
      title: 'Categories',
      headers: ['category_id', 'name', 'parent_id', 'sort_order', 'active'],
    },
    {
      // Nhà cung cấp
      title: 'Suppliers',
      headers: ['supplier_id', 'name', 'phone', 'email', 'address', 'payment_terms', 'note'],
    },
    {
      // Sản phẩm — variant_id để trống ở v1, dùng khi nâng cấp tính năng biến thể
      title: 'Products',
      headers: [
        'product_id', 'sku', 'barcode', 'name', 'category_id', 'unit',
        'sell_price', 'cost_price', 'min_price', 'tax_rate', 'weight',
        'stock_track', 'variant_id', 'active', 'image_url', 'description',
      ],
    },
    {
      // Bảng giá theo nhóm khách (retail / wholesale / vip / staff)
      title: 'PriceLists',
      headers: ['price_id', 'product_id', 'sku', 'price_type', 'sell_price', 'effective_from', 'effective_to', 'active'],
    },
    {
      // Khuyến mãi — v1 chỉ hỗ trợ type: percent | fixed
      // applicable_type: all | sku | category  +  applicable_ref: SKU hoặc category_id tương ứng
      title: 'Discounts',
      headers: [
        'discount_id', 'name', 'type', 'value',
        'min_qty', 'min_order_value',
        'applicable_type', 'applicable_ref',
        'start_date', 'end_date', 'active',
      ],
    },
    {
      // Tồn kho theo chi nhánh — reserved_qty tính on-demand, không lưu để tránh lệch
      // variant_id để trống ở v1
      title: 'Inventory',
      headers: [
        'inventory_id', 'product_id', 'sku', 'variant_id', 'branch_id',
        'stock_qty', 'min_stock', 'unit_cost', 'last_received_at', 'last_updated',
      ],
    },
    {
      // Nhập/xuất kho — mỗi biến động tồn kho là 1 dòng (audit trail)
      // type: purchase_in | sale_out | transfer_in | transfer_out | adjustment | return_in
      title: 'StockMovements',
      headers: [
        'movement_id', 'movement_no', 'type', 'product_id', 'sku', 'variant_id',
        'qty', 'unit_cost', 'branch_id', 'supplier_id',
        'reference_no', 'employee_id', 'reason', 'created_at',
      ],
    },
    {
      // Khách hàng — total_orders / total_spent KHÔNG lưu ở đây, tính từ Orders
      title: 'Customers',
      headers: [
        'customer_id', 'customer_code', 'name', 'phone', 'email',
        'address', 'birthday', 'customer_type',
        'credit_limit', 'debt_amount', 'loyalty_points',
        'note', 'created_at',
      ],
    },
    {
      // Đơn hàng
      // status: draft | confirmed | processing | completed | cancelled | refunded
      // channel: pos | online | phone | zalo
      // is_return: TRUE/FALSE — nếu TRUE thì original_order_id trỏ về đơn gốc
      title: 'Orders',
      headers: [
        'order_id', 'order_no', 'created_at', 'status',
        'customer_id', 'customer_name', 'branch_id', 'employee_id', 'channel',
        'subtotal', 'discount_amount', 'shipping_fee', 'tax_amount',
        'total_amount', 'paid_amount', 'debt_amount',
        'is_return', 'original_order_id',
        'points_earned', 'points_redeemed',
        'note', 'updated_at',
      ],
    },
    {
      // Chi tiết dòng đơn hàng
      // Đơn trả hàng dùng qty âm, is_return=TRUE trên Orders
      title: 'OrderItems',
      headers: [
        'item_id', 'order_id', 'order_no', 'line_no',
        'product_id', 'sku', 'variant_id', 'product_name',
        'qty', 'unit_price', 'discount_pct', 'line_discount',
        'tax_rate', 'tax_amount', 'line_total',
        'employee_id',
      ],
    },
    {
      // Thanh toán — 1 đơn có thể có nhiều payment (split payment, trả nhiều đợt)
      // method: cash | card | bank_transfer | momo | vnpay | zalopay | debt
      title: 'Payments',
      headers: ['payment_id', 'order_id', 'order_no', 'method', 'amount', 'paid_at', 'cashier_id', 'reference_no', 'note'],
    },
    {
      // Chi nhánh
      title: 'Branches',
      headers: ['branch_id', 'name', 'address', 'phone', 'manager_id', 'active'],
    },
    {
      // Nhân viên
      // role: owner | manager | sales | cashier | warehouse
      title: 'Employees',
      headers: ['employee_id', 'employee_code', 'name', 'phone', 'role', 'branch_id', 'commission_pct', 'active', 'hire_date', 'note'],
    },
    {
      // Cài đặt hệ thống dạng key-value
      // Oni seed sẵn: schema_version, shop_name, currency, tax_rate, invoice_prefix, low_stock_threshold, allow_negative_stock, default_price_type
      title: 'Settings',
      headers: ['key', 'value', 'description'],
    },
  ];
}

export const ONI_SCHEMA_VERSION = '1';

export const ONI_DEFAULT_SETTINGS: Array<[string, string, string]> = [
  ['schema_version', ONI_SCHEMA_VERSION, 'Phiên bản schema ONI — không xóa/sửa'],
  ['shop_name', '', 'Tên cửa hàng'],
  ['currency', 'VND', 'Đơn vị tiền tệ'],
  ['tax_rate', '0', 'Thuế GTGT mặc định (%, 0 = không tính thuế)'],
  ['invoice_prefix', 'ORD', 'Tiền tố số đơn hàng (vd: ORD → ORD-2025-0001)'],
  ['low_stock_threshold', '5', 'Cảnh báo hết hàng khi tồn kho xuống dưới mức này'],
  ['allow_negative_stock', 'false', 'Cho phép bán khi hết hàng (true/false)'],
  ['default_price_type', 'retail', 'Loại giá mặc định khi tạo đơn'],
];
