-- migration: 20260531090000_backpopulate_asset_branch
-- [NOTE] This migration was moved/commented out because "assets" and "asset_depreciations" 
-- reside in the separate business/operational databases (configured per tenant via adapters), 
-- not in the Supabase configurations database.
-- 
-- The actual migration logic below must be executed directly on the tenant's operational database:
-- 
-- UPDATE public.assets a
-- SET branch_id = (
--   SELECT s.id 
--   FROM public.shops s 
--   WHERE s.tenant_id = a.tenant_id 
--   ORDER BY s.created_at ASC 
--   LIMIT 1
-- )
-- WHERE a.branch_id IS NULL OR a.branch_id = '';
-- 
-- UPDATE public.asset_depreciations ad
-- SET branch_id = (
--   SELECT s.id 
--   FROM public.shops s 
--   WHERE s.tenant_id = ad.tenant_id 
--   ORDER BY s.created_at ASC 
--   LIMIT 1
-- )
-- WHERE ad.branch_id IS NULL OR ad.branch_id = '';
